# Generated by Django 2.2.5 on 2021-09-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='대표이미지'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('남성', '남성'), ('여성', '여성'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('경기도', '경기도'), ('강원도', '강원도'), ('충청남도', '충청남도'), ('충청북도', '충청북도'), ('전라남도', '전라남도'), ('전라북도', '전라북도'), ('경상남도', '경상남도'), ('경상북도', '경상북도'), ('제주도', '제주도')], max_length=20, null=True),
        ),
    ]
