# Generated by Django 2.2.5 on 2021-09-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210907_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Total_hoursOfExercise',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Total_hoursOfVisits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='resent_checkIn_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='resent_checkOut_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
