# Generated by Django 2.2.5 on 2021-09-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210907_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='이용권 만료날짜'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Total_hoursOfExercise',
            field=models.IntegerField(blank=True, null=True, verbose_name='총 운동 시간'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Total_hoursOfVisits',
            field=models.IntegerField(blank=True, null=True, verbose_name='총 방문일 수'),
        ),
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='대표이미지', verbose_name='대표이미지'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='간략소개'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=80, null=True, verbose_name='지역(시)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('남성', '남성'), ('여성', '여성'), ('other', 'Other')], max_length=10, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('경기도', '경기도'), ('강원도', '강원도'), ('충청남도', '충청남도'), ('충청북도', '충청북도'), ('전라남도', '전라남도'), ('전라북도', '전라북도'), ('경상남도', '경상남도'), ('경상북도', '경상북도'), ('제주도', '제주도')], max_length=20, null=True, verbose_name='지역(도)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='resent_checkIn_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='최근 입실시간'),
        ),
        migrations.AlterField(
            model_name='client',
            name='resent_checkOut_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='최근 퇴실시간'),
        ),
    ]
