# Generated by Django 2.2.5 on 2021-09-21 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': '헬스장 사진'},
        ),
    ]
