SELECT  fh.FLAVOR
FROM  (SELECT FLAVOR, SUM(TOTAL_ORDER) SUM_ORDER
       FROM FIRST_HALF 
       GROUP BY FLAVOR) fh
    JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) SUM_ORDER
       FROM JULY 
       GROUP BY FLAVOR) j
    ON fh.FLAVOR = j.FLAVOR
ORDER BY (fh.SUM_ORDER + j.SUM_ORDER) DESC LIMIT 3;